### ISSUE TITLE
Ignoring DATAIKU_ANSIBLE_DSS_HOST environment variable

### ISSUE THREAD

**Issue by valunf** [dataiku/dataiku-ansible-collection#20]
https://github.com/dataiku/dataiku-ansible-collection/blob/cb229e3257a8b79121c5da61408842a41400dc0f/plugins/module_utils/dataiku_utils.py#L107-L113

line 113 should be `client = DSSClient(f"http://{host}:{port}", api_key=api_key)`

**Comment by duckie** [comment]
Good catch, thanks ! We will fix it
