### ISSUE TITLE
Question - FleetManager

### ISSUE THREAD

**Issue by funes79** [dataiku/dataiku-ansible-collection#22]
Current version of the FleetManager does not refer to this newer repo, could you add examples (here or to the documentation) how to use this collection in Setup Actions? 
![image](https://github.com/user-attachments/assets/fff9cf59-6054-466d-b620-7002c624556f)

Thanks!

**Comment by duckie** [comment]
Hello @funes79 

It does not refer to it but the newest versions of Fleet Manager are indeed using it. Duly noted, we will update the documentation to match the more modern approach. However, current documentation is still valid.

If you want to conform to the collection style, you can use this syntax:

```
---
- dataiku.dss.dss_user:
    login: admin
    state: absent
```

If you want more info for a given module, install the collection in a local environment and run the following command:

```
ansible-doc dataiku.dss.dss_user
```
