### ISSUE TITLE
dss_group.py is missing some permissions as inputs

### ISSUE THREAD

**Issue by adilkhanekt** [dataiku/dataiku-ansible-collection#29]
Hello.
I have raised PR with the fix.
Could you please take a look?

https://github.com/dataiku/dataiku-ansible-collection/pull/28

**Comment by aardon-dku** [comment]
Hello @adilkhanekt, thank you for raising this. We have reviewed and merged your fix.

The fix will be packaged in future DSS releases, but at the moment the easiest way to access it is to reference the collection from this git repository

**Comment by aardon-dku** [comment]
Hello @adilkhanekt, thank you for raising this. We have reviewed and merged your fix.

The fix will be packaged in future DSS releases, but at the moment the easiest way to access it is to reference the collection from this git repository
